name=TinyNBD
version=0.1.0
author=Phil Schatzmann
maintainer=Phil Schatzmann <phil.schatzmann@gmail.com>
sentence=Header-only nbd (Network Block Device) server using the Arduino networking API
paragraph=Export RAM/PSRAM, SD cards (SD and SD_MMC), ESP32 flash partitions or image files as network block devices to Linux (nbd-client), qemu or nbdkit tools.
category=Communication
url=https://github.com/pschatzmann/TinyNBD
architectures=*
includes=NBD.h
